#ifndef WASMOPCODEDISPATCHER_HPP
#define WASMOPCODEDISPATCHER_HPP
#include "WasmType.hpp"
#include "WasmOpcode.hpp"
namespace WASM {

class OpcodeDispatcher
{
private:
	// Concrete opcode dispatches:
	virtual void dispatchUnreachable() = 0;
	virtual void dispatchNop() = 0;
	virtual void dispatchBlock(const BlockType& arg) = 0;
	virtual void dispatchLoop(const BlockType& arg) = 0;
	virtual void dispatchIf(const BlockType& arg) = 0;
	virtual void dispatchElse() = 0;
	virtual void dispatchThrow(TagIdx arg) = 0;
	virtual void dispatchThrowRef() = 0;
	virtual void dispatchEnd() = 0;
	virtual void dispatchBr(LabelIdx arg) = 0;
	virtual void dispatchBrIf(LabelIdx arg) = 0;
	virtual void dispatchBrTable(std::vector<LabelIdx>&& arg1, LabelIdx arg2) = 0;
	virtual void dispatchReturn() = 0;
	virtual void dispatchCall(FuncIdx arg) = 0;
	virtual void dispatchCallIndirect(TypeIdx arg1, TableIdx arg2) = 0;
	virtual void dispatchReturnCall(FuncIdx arg) = 0;
	virtual void dispatchReturnCallIndirect(TypeIdx arg1, TableIdx arg2) = 0;
	virtual void dispatchCallRef(FuncIdx arg) = 0;
	virtual void dispatchReturnCallRef(FuncIdx arg) = 0;
	virtual void dispatchTryTable(const BlockType& arg1, std::vector<CatchClause>&& arg2) = 0;
	virtual void dispatchDrop() = 0;
	virtual void dispatchSelect() = 0;
	virtual void dispatchSelectT(std::vector<ValueType>&& arg) = 0;
	virtual void dispatchLocalGet(LocalIdx arg) = 0;
	virtual void dispatchLocalSet(LocalIdx arg) = 0;
	virtual void dispatchLocalTee(LocalIdx arg) = 0;
	virtual void dispatchGlobalGet(GlobalIdx arg) = 0;
	virtual void dispatchGlobalSet(GlobalIdx arg) = 0;
	virtual void dispatchTableGet(TableIdx arg) = 0;
	virtual void dispatchTableSet(TableIdx arg) = 0;
	virtual void dispatchI32Load(MemArg addr) = 0;
	virtual void dispatchI64Load(MemArg addr) = 0;
	virtual void dispatchF32Load(MemArg addr) = 0;
	virtual void dispatchF64Load(MemArg addr) = 0;
	virtual void dispatchI32Load8S(MemArg addr) = 0;
	virtual void dispatchI32Load8U(MemArg addr) = 0;
	virtual void dispatchI32Load16S(MemArg addr) = 0;
	virtual void dispatchI32Load16U(MemArg addr) = 0;
	virtual void dispatchI64Load8S(MemArg addr) = 0;
	virtual void dispatchI64Load8U(MemArg addr) = 0;
	virtual void dispatchI64Load16S(MemArg addr) = 0;
	virtual void dispatchI64Load16U(MemArg addr) = 0;
	virtual void dispatchI64Load32S(MemArg addr) = 0;
	virtual void dispatchI64Load32U(MemArg addr) = 0;
	virtual void dispatchI32Store(MemArg addr) = 0;
	virtual void dispatchI64Store(MemArg addr) = 0;
	virtual void dispatchF32Store(MemArg addr) = 0;
	virtual void dispatchF64Store(MemArg addr) = 0;
	virtual void dispatchI32Store8(MemArg addr) = 0;
	virtual void dispatchI32Store16(MemArg addr) = 0;
	virtual void dispatchI64Store8(MemArg addr) = 0;
	virtual void dispatchI64Store16(MemArg addr) = 0;
	virtual void dispatchI64Store32(MemArg addr) = 0;
	virtual void dispatchMemorySize(MemIdx arg) = 0;
	virtual void dispatchMemoryGrow(MemIdx arg) = 0;
	virtual void dispatchI32Const(int32_t arg) = 0;
	virtual void dispatchI64Const(int64_t arg) = 0;
	virtual void dispatchF32Const(float arg) = 0;
	virtual void dispatchF64Const(double arg) = 0;
	virtual void dispatchI32Eqz() = 0;
	virtual void dispatchI32Eq() = 0;
	virtual void dispatchI32Ne() = 0;
	virtual void dispatchI32LtS() = 0;
	virtual void dispatchI32LtU() = 0;
	virtual void dispatchI32GtS() = 0;
	virtual void dispatchI32GtU() = 0;
	virtual void dispatchI32LeS() = 0;
	virtual void dispatchI32LeU() = 0;
	virtual void dispatchI32GeS() = 0;
	virtual void dispatchI32GeU() = 0;
	virtual void dispatchI64Eqz() = 0;
	virtual void dispatchI64Eq() = 0;
	virtual void dispatchI64Ne() = 0;
	virtual void dispatchI64LtS() = 0;
	virtual void dispatchI64LtU() = 0;
	virtual void dispatchI64GtS() = 0;
	virtual void dispatchI64GtU() = 0;
	virtual void dispatchI64LeS() = 0;
	virtual void dispatchI64LeU() = 0;
	virtual void dispatchI64GeS() = 0;
	virtual void dispatchI64GeU() = 0;
	virtual void dispatchF32Eq() = 0;
	virtual void dispatchF32Ne() = 0;
	virtual void dispatchF32Lt() = 0;
	virtual void dispatchF32Gt() = 0;
	virtual void dispatchF32Le() = 0;
	virtual void dispatchF32Ge() = 0;
	virtual void dispatchF64Eq() = 0;
	virtual void dispatchF64Ne() = 0;
	virtual void dispatchF64Lt() = 0;
	virtual void dispatchF64Gt() = 0;
	virtual void dispatchF64Le() = 0;
	virtual void dispatchF64Ge() = 0;
	virtual void dispatchI32Clz() = 0;
	virtual void dispatchI32Ctz() = 0;
	virtual void dispatchI32Popcnt() = 0;
	virtual void dispatchI32Add() = 0;
	virtual void dispatchI32Sub() = 0;
	virtual void dispatchI32Mul() = 0;
	virtual void dispatchI32DivS() = 0;
	virtual void dispatchI32DivU() = 0;
	virtual void dispatchI32RemS() = 0;
	virtual void dispatchI32RemU() = 0;
	virtual void dispatchI32And() = 0;
	virtual void dispatchI32Or() = 0;
	virtual void dispatchI32Xor() = 0;
	virtual void dispatchI32Shl() = 0;
	virtual void dispatchI32ShrS() = 0;
	virtual void dispatchI32ShrU() = 0;
	virtual void dispatchI32Rotl() = 0;
	virtual void dispatchI32Rotr() = 0;
	virtual void dispatchI64Clz() = 0;
	virtual void dispatchI64Ctz() = 0;
	virtual void dispatchI64Popcnt() = 0;
	virtual void dispatchI64Add() = 0;
	virtual void dispatchI64Sub() = 0;
	virtual void dispatchI64Mul() = 0;
	virtual void dispatchI64DivS() = 0;
	virtual void dispatchI64DivU() = 0;
	virtual void dispatchI64RemS() = 0;
	virtual void dispatchI64RemU() = 0;
	virtual void dispatchI64And() = 0;
	virtual void dispatchI64Or() = 0;
	virtual void dispatchI64Xor() = 0;
	virtual void dispatchI64Shl() = 0;
	virtual void dispatchI64ShrS() = 0;
	virtual void dispatchI64ShrU() = 0;
	virtual void dispatchI64Rotl() = 0;
	virtual void dispatchI64Rotr() = 0;
	virtual void dispatchF32Abs() = 0;
	virtual void dispatchF32Neg() = 0;
	virtual void dispatchF32Ceil() = 0;
	virtual void dispatchF32Floor() = 0;
	virtual void dispatchF32Trunc() = 0;
	virtual void dispatchF32Nearest() = 0;
	virtual void dispatchF32Sqrt() = 0;
	virtual void dispatchF32Add() = 0;
	virtual void dispatchF32Sub() = 0;
	virtual void dispatchF32Mul() = 0;
	virtual void dispatchF32Div() = 0;
	virtual void dispatchF32Min() = 0;
	virtual void dispatchF32Max() = 0;
	virtual void dispatchF32Copysign() = 0;
	virtual void dispatchF64Abs() = 0;
	virtual void dispatchF64Neg() = 0;
	virtual void dispatchF64Ceil() = 0;
	virtual void dispatchF64Floor() = 0;
	virtual void dispatchF64Trunc() = 0;
	virtual void dispatchF64Nearest() = 0;
	virtual void dispatchF64Sqrt() = 0;
	virtual void dispatchF64Add() = 0;
	virtual void dispatchF64Sub() = 0;
	virtual void dispatchF64Mul() = 0;
	virtual void dispatchF64Div() = 0;
	virtual void dispatchF64Min() = 0;
	virtual void dispatchF64Max() = 0;
	virtual void dispatchF64Copysign() = 0;
	virtual void dispatchI32WrapI64() = 0;
	virtual void dispatchI32TruncF32S() = 0;
	virtual void dispatchI32TruncF32U() = 0;
	virtual void dispatchI32TruncF64S() = 0;
	virtual void dispatchI32TruncF64U() = 0;
	virtual void dispatchI64ExtendI32S() = 0;
	virtual void dispatchI64ExtendI32U() = 0;
	virtual void dispatchI64TruncF32S() = 0;
	virtual void dispatchI64TruncF32U() = 0;
	virtual void dispatchI64TruncF64S() = 0;
	virtual void dispatchI64TruncF64U() = 0;
	virtual void dispatchF32ConvertI32S() = 0;
	virtual void dispatchF32ConvertI32U() = 0;
	virtual void dispatchF32ConvertI64S() = 0;
	virtual void dispatchF32ConvertI64U() = 0;
	virtual void dispatchF32DemoteF64() = 0;
	virtual void dispatchF64ConvertI32S() = 0;
	virtual void dispatchF64ConvertI32U() = 0;
	virtual void dispatchF64ConvertI64S() = 0;
	virtual void dispatchF64ConvertI64U() = 0;
	virtual void dispatchF64PromoteF32() = 0;
	virtual void dispatchI32ReinterpretF32() = 0;
	virtual void dispatchI64ReinterpretF64() = 0;
	virtual void dispatchF32ReinterpretI32() = 0;
	virtual void dispatchF64ReinterpretI64() = 0;
	virtual void dispatchI32Extend8S() = 0;
	virtual void dispatchI32Extend16S() = 0;
	virtual void dispatchI64Extend8S() = 0;
	virtual void dispatchI64Extend16S() = 0;
	virtual void dispatchI64Extend32S() = 0;
	virtual void dispatchRefNull(const HeapType& arg) = 0;
	virtual void dispatchRefIsNull() = 0;
	virtual void dispatchRefFunc(FuncIdx arg) = 0;
	virtual void dispatchRefEq() = 0;
	virtual void dispatchRefAsNonNull() = 0;
	virtual void dispatchBrOnNull(LabelIdx arg) = 0;
	virtual void dispatchBrOnNonNull(LabelIdx arg) = 0;
	// Prefix dispatches
	void dispatchPrefixGC(WasmStream& stream, GCOpcode opcode);
	void dispatchPrefixMisc(WasmStream& stream, MiscOpcode opcode);
	void dispatchPrefixSIMD(WasmStream& stream, SIMDOpcode opcode);
	void dispatchPrefixAtomic(WasmStream& stream, AtomicOpcode opcode);
	// Helper for dispatching code
	void dispatchOpcode(WasmStream& stream, Opcode opcode);
public:
	~OpcodeDispatcher() = default;
	void readCode(WasmStream& stream);
};

}
#endif // WASMOPCODEDISPATCHER_HPP
