#ifndef LIBJITOPCODEDISPATCHER_HPP
#define LIBJITOPCODEDISPATCHER_HPP

#include "../WasmBase/WasmModuleInstance.hpp"
#include "../WasmBase/WasmOpcodeDispatcher.hpp"
#include "LibJitTypeTranslation.hpp"
#include <jit/jit.h>
#include <vector>

namespace LibJIT {

struct ControlBlock {
	enum Kind { Block, Loop, If };
	Kind kind;

	// For Block/If: a forward label at the end (bound when we see 'end').
	// For Loop: a backward label at the start (bound when we see 'loop').
	// A 'br N' instruction branches to controlStack[top - N].label.
	jit_label_t label;

	// For 'if': we also need a label for the 'else' branch, so that
	// the condition check can jump forward to it if false.
	jit_label_t elseLabel;

	// The value stack depth when this block was entered. Used to
	// validate and restore the stack at 'else' and 'end' boundaries.
	size_t stackDepth;

	// The types this block is expected to produce on exit.
	// A 'br' to this block must leave these types on the stack.
	std::vector<WASM::StorageType> resultTypes;
	std::vector<WASM::StorageType> paramTypes;
	std::vector<jit_value_t> resultSlots;
	std::vector<jit_value_t> paramSlots;
	bool hasElse = false;
};

// Drives WASM::OpcodeDispatcher::readCode for LibJIT: decodes the bytecode
// stream and emits jit_insn_* into the current jit_function_t. Holds the
// transient compilation state (locals, stacks, module context) that
// ModuleCompiler used to pass through a monolithic dispatchOpcode.
class OpcodeDispatcher : public WASM::OpcodeDispatcher
{
private:
	jit_context_t context;
	jit_function_t function;
	LibJitTypeTranslator& typeTranslator;
	WASM::ModuleInstance& instance;
	WASM::ModuleInstanceInternals& internals;
	const WASM::Module& module;
	const WASM::FuncType& currentFunc;
	uint32_t importedFuncCount;
	std::vector<jit_value_t>& locals;
	std::vector<jit_value_t>& valueStack;
	std::vector<ControlBlock>& controlStack;

	void pushValue(jit_value_t v);
	jit_value_t popValue();
	jit_value_t zeroConstantForType(jit_type_t t);
	jit_value_t castRefValue(jit_value_t value, jit_type_t targetType);
	jit_value_t refAsVoidPtr(jit_value_t value);
	jit_value_t typedNullRef(jit_type_t refType);
	jit_value_t emitRefTypeTest(jit_value_t ref, const WASM::HeapType& heapType, bool nullable);
	jit_type_t tableElementJitType(WASM::TableIdx arg) const;
	jit_type_t jitRefTypeForHeapType(const WASM::HeapType& ht, bool nullable);
	jit_type_t structRefType(WASM::TypeIdx arg, bool nullable) const;
	jit_type_t arrayRefType(WASM::TypeIdx arg, bool nullable) const;
	const WASM::StructType& structTypeForIndex(WASM::TypeIdx arg) const;
	const WASM::ArrayType& arrayTypeForIndex(WASM::TypeIdx arg) const;
	jit_type_t arrayElementJitType(WASM::TypeIdx arg) const;
	jit_nint structFieldOffset(WASM::TypeIdx arg, uint32_t fieldIndex) const;
	jit_nint arrayLengthOffset(WASM::TypeIdx arg) const;
	jit_nint arrayDataOffset(WASM::TypeIdx arg) const;
	jit_value_t packReturnValues(jit_type_t returnType, size_t resultCount);
	void pushCallResults(const WASM::FuncType& calleeSig, jit_type_t calleeJitSig, jit_value_t ret);
	std::vector<WASM::StorageType> parameterTypesForBlockType(const WASM::BlockType& bt) const;
	std::vector<jit_value_t> createSlotsForTypes(const std::vector<WASM::StorageType>& types);
	void storeStackTopToSlots(const std::vector<jit_value_t>& slots);
	void restoreValuesFromSlots(const std::vector<jit_value_t>& slots);
	void resizeValueStack(size_t newSize);
	ControlBlock& branchTarget(WASM::LabelIdx arg);
	const std::vector<WASM::StorageType>& branchTypesForTarget(const ControlBlock& target) const;
	const std::vector<jit_value_t>& branchSlotsForTarget(const ControlBlock& target) const;
	void emitBranchToTarget(ControlBlock& target);
	WASM::TypeIdx functionTypeIndexForFunc(WASM::FuncIdx funcIdx) const;
	const WASM::FuncType& functionSignatureForType(WASM::TypeIdx typeIdx) const;
	jit_value_t callablePointerForFuncIndex(WASM::FuncIdx funcIdx);
	void dispatchCallThroughCallable(jit_value_t callablePtr, WASM::TypeIdx typeIdx);
	void emitTrapUnreachable();
	std::vector<WASM::StorageType> storageTypesForBlockType(const WASM::BlockType& bt) const;

	jit_value_t vmContextValue();
	jit_value_t checkedTableIndex(jit_value_t table, jit_value_t index, const char* opname);
	// Emits code yielding the LinearMemory* for a (constant) memory index.
	jit_value_t memoryPointerForIndex(WASM::MemIdx memidx);
	// Emits code yielding the TableInstance* for a (constant) table index.
	jit_value_t tablePointerForIndex(WASM::TableIdx tableidx);
	// Emits a runtime check that `callablePtr`'s canonical type id matches the
	// module-local type index `typeIdx` (id fast path, registry fallback).
	void emitCallableTypeCheck(jit_value_t callablePtr, WASM::TypeIdx typeIdx);
	jit_value_t effectiveMemoryAddress(const WASM::MemArg& ma, jit_nint accessSize);
	WASM::GlobalType globalTypeForIndex(WASM::GlobalIdx idx) const;

public:
	OpcodeDispatcher(jit_context_t context, jit_function_t function,
					 LibJitTypeTranslator& typeTranslator,
					 WASM::ModuleInstance& instance,
					 WASM::ModuleInstanceInternals& internals,
					 const WASM::Module& module, const WASM::FuncType& currentFunc,
					 uint32_t importedFuncCount,
					 std::vector<jit_value_t>& locals,
					 std::vector<jit_value_t>& valueStack,
					 std::vector<ControlBlock>& controlStack);

	// Call after readCode() to emit return from the implicit function body (Wasm validation
	// guarantees the value stack matches currentFunc.results).
	void emitImplicitFunctionReturn();

	// OpcodeDispatcher interface
protected:
	// `internals.translatedTypes` is parallel to `module.types` (filled in translateTypes).
	jit_type_t jitTypeForTypeIdx(WASM::TypeIdx idx) const;
	jit_type_t jitTypeForValueType(const WASM::ValueType& vt);

	void dispatchUnreachable() override;
	void dispatchNop() override;
	void dispatchBlock(const WASM::BlockType& arg) override;
	void dispatchLoop(const WASM::BlockType& arg) override;
	void dispatchIf(const WASM::BlockType& arg) override;
	void dispatchElse() override;
	void dispatchThrow(WASM::TagIdx arg) override;
	void dispatchThrowRef() override;
	void dispatchEnd() override;
	void dispatchBr(WASM::LabelIdx arg) override;
	void dispatchBrIf(WASM::LabelIdx arg) override;
	void dispatchBrTable(std::vector<WASM::LabelIdx>&& arg1, WASM::LabelIdx arg2) override;
	void dispatchReturn() override;
	void dispatchCall(WASM::FuncIdx arg) override;
	void dispatchCallIndirect(WASM::TypeIdx arg1, WASM::TableIdx arg2) override;
	void dispatchReturnCall(WASM::FuncIdx arg) override;
	void dispatchReturnCallIndirect(WASM::TypeIdx arg1, WASM::TableIdx arg2) override;
	void dispatchCallRef(WASM::TypeIdx arg) override;
	void dispatchReturnCallRef(WASM::TypeIdx arg) override;
	void dispatchTryTable(const WASM::BlockType& arg1, std::vector<WASM::CatchClause>&& arg2) override;
	void dispatchDrop() override;
	void dispatchSelect() override;
	void dispatchSelectT(std::vector<WASM::ValueType>&& arg) override;
	void dispatchLocalGet(WASM::LocalIdx arg) override;
	void dispatchLocalSet(WASM::LocalIdx arg) override;
	void dispatchLocalTee(WASM::LocalIdx arg) override;
	void dispatchGlobalGet(WASM::GlobalIdx arg) override;
	void dispatchGlobalSet(WASM::GlobalIdx arg) override;
	void dispatchTableGet(WASM::TableIdx arg) override;
	void dispatchTableSet(WASM::TableIdx arg) override;
	void dispatchI32Load(WASM::MemArg addr) override;
	void dispatchI64Load(WASM::MemArg addr) override;
	void dispatchF32Load(WASM::MemArg addr) override;
	void dispatchF64Load(WASM::MemArg addr) override;
	void dispatchI32Load8S(WASM::MemArg addr) override;
	void dispatchI32Load8U(WASM::MemArg addr) override;
	void dispatchI32Load16S(WASM::MemArg addr) override;
	void dispatchI32Load16U(WASM::MemArg addr) override;
	void dispatchI64Load8S(WASM::MemArg addr) override;
	void dispatchI64Load8U(WASM::MemArg addr) override;
	void dispatchI64Load16S(WASM::MemArg addr) override;
	void dispatchI64Load16U(WASM::MemArg addr) override;
	void dispatchI64Load32S(WASM::MemArg addr) override;
	void dispatchI64Load32U(WASM::MemArg addr) override;
	void dispatchI32Store(WASM::MemArg addr) override;
	void dispatchI64Store(WASM::MemArg addr) override;
	void dispatchF32Store(WASM::MemArg addr) override;
	void dispatchF64Store(WASM::MemArg addr) override;
	void dispatchI32Store8(WASM::MemArg addr) override;
	void dispatchI32Store16(WASM::MemArg addr) override;
	void dispatchI64Store8(WASM::MemArg addr) override;
	void dispatchI64Store16(WASM::MemArg addr) override;
	void dispatchI64Store32(WASM::MemArg addr) override;
	void dispatchMemorySize(WASM::MemIdx arg) override;
	void dispatchMemoryGrow(WASM::MemIdx arg) override;
	void dispatchI32Const(int32_t arg) override;
	void dispatchI64Const(int64_t arg) override;
	void dispatchF32Const(float arg) override;
	void dispatchF64Const(double arg) override;
	void dispatchI32Eqz() override;
	void dispatchI32Eq() override;
	void dispatchI32Ne() override;
	void dispatchI32LtS() override;
	void dispatchI32LtU() override;
	void dispatchI32GtS() override;
	void dispatchI32GtU() override;
	void dispatchI32LeS() override;
	void dispatchI32LeU() override;
	void dispatchI32GeS() override;
	void dispatchI32GeU() override;
	void dispatchI64Eqz() override;
	void dispatchI64Eq() override;
	void dispatchI64Ne() override;
	void dispatchI64LtS() override;
	void dispatchI64LtU() override;
	void dispatchI64GtS() override;
	void dispatchI64GtU() override;
	void dispatchI64LeS() override;
	void dispatchI64LeU() override;
	void dispatchI64GeS() override;
	void dispatchI64GeU() override;
	void dispatchF32Eq() override;
	void dispatchF32Ne() override;
	void dispatchF32Lt() override;
	void dispatchF32Gt() override;
	void dispatchF32Le() override;
	void dispatchF32Ge() override;
	void dispatchF64Eq() override;
	void dispatchF64Ne() override;
	void dispatchF64Lt() override;
	void dispatchF64Gt() override;
	void dispatchF64Le() override;
	void dispatchF64Ge() override;
	void dispatchI32Clz() override;
	void dispatchI32Ctz() override;
	void dispatchI32Popcnt() override;
	void dispatchI32Add() override;
	void dispatchI32Sub() override;
	void dispatchI32Mul() override;
	void dispatchI32DivS() override;
	void dispatchI32DivU() override;
	void dispatchI32RemS() override;
	void dispatchI32RemU() override;
	void dispatchI32And() override;
	void dispatchI32Or() override;
	void dispatchI32Xor() override;
	void dispatchI32Shl() override;
	void dispatchI32ShrS() override;
	void dispatchI32ShrU() override;
	void dispatchI32Rotl() override;
	void dispatchI32Rotr() override;
	void dispatchI64Clz() override;
	void dispatchI64Ctz() override;
	void dispatchI64Popcnt() override;
	void dispatchI64Add() override;
	void dispatchI64Sub() override;
	void dispatchI64Mul() override;
	void dispatchI64DivS() override;
	void dispatchI64DivU() override;
	void dispatchI64RemS() override;
	void dispatchI64RemU() override;
	void dispatchI64And() override;
	void dispatchI64Or() override;
	void dispatchI64Xor() override;
	void dispatchI64Shl() override;
	void dispatchI64ShrS() override;
	void dispatchI64ShrU() override;
	void dispatchI64Rotl() override;
	void dispatchI64Rotr() override;
	void dispatchF32Abs() override;
	void dispatchF32Neg() override;
	void dispatchF32Ceil() override;
	void dispatchF32Floor() override;
	void dispatchF32Trunc() override;
	void dispatchF32Nearest() override;
	void dispatchF32Sqrt() override;
	void dispatchF32Add() override;
	void dispatchF32Sub() override;
	void dispatchF32Mul() override;
	void dispatchF32Div() override;
	void dispatchF32Min() override;
	void dispatchF32Max() override;
	void dispatchF32Copysign() override;
	void dispatchF64Abs() override;
	void dispatchF64Neg() override;
	void dispatchF64Ceil() override;
	void dispatchF64Floor() override;
	void dispatchF64Trunc() override;
	void dispatchF64Nearest() override;
	void dispatchF64Sqrt() override;
	void dispatchF64Add() override;
	void dispatchF64Sub() override;
	void dispatchF64Mul() override;
	void dispatchF64Div() override;
	void dispatchF64Min() override;
	void dispatchF64Max() override;
	void dispatchF64Copysign() override;
	void dispatchI32WrapI64() override;
	void dispatchI32TruncF32S() override;
	void dispatchI32TruncF32U() override;
	void dispatchI32TruncF64S() override;
	void dispatchI32TruncF64U() override;
	void dispatchI64ExtendI32S() override;
	void dispatchI64ExtendI32U() override;
	void dispatchI64TruncF32S() override;
	void dispatchI64TruncF32U() override;
	void dispatchI64TruncF64S() override;
	void dispatchI64TruncF64U() override;
	void dispatchF32ConvertI32S() override;
	void dispatchF32ConvertI32U() override;
	void dispatchF32ConvertI64S() override;
	void dispatchF32ConvertI64U() override;
	void dispatchF32DemoteF64() override;
	void dispatchF64ConvertI32S() override;
	void dispatchF64ConvertI32U() override;
	void dispatchF64ConvertI64S() override;
	void dispatchF64ConvertI64U() override;
	void dispatchF64PromoteF32() override;
	void dispatchI32ReinterpretF32() override;
	void dispatchI64ReinterpretF64() override;
	void dispatchF32ReinterpretI32() override;
	void dispatchF64ReinterpretI64() override;
	void dispatchI32Extend8S() override;
	void dispatchI32Extend16S() override;
	void dispatchI64Extend8S() override;
	void dispatchI64Extend16S() override;
	void dispatchI64Extend32S() override;
	void dispatchRefNull(const WASM::HeapType& arg) override;
	void dispatchRefIsNull() override;
	void dispatchRefFunc(WASM::FuncIdx arg) override;
	void dispatchRefEq() override;
	void dispatchRefAsNonNull() override;
	void dispatchBrOnNull(WASM::LabelIdx arg) override;
	void dispatchBrOnNonNull(WASM::LabelIdx arg) override;
	void dispatchStructNew(WASM::TypeIdx arg) override;
	void dispatchStructNewDefault(WASM::TypeIdx arg) override;
	void dispatchStructGet(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchStructGetS(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchStructGetU(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchStructSet(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchArrayNew(WASM::TypeIdx arg) override;
	void dispatchArrayNewDefault(WASM::TypeIdx arg) override;
	void dispatchArrayNewFixed(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchArrayNewData(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchArrayNewElem(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchArrayGet(WASM::TypeIdx arg) override;
	void dispatchArrayGetS(WASM::TypeIdx arg) override;
	void dispatchArrayGetU(WASM::TypeIdx arg) override;
	void dispatchArraySet(WASM::TypeIdx arg) override;
	void dispatchArrayLen() override;
	void dispatchArrayFill(WASM::TypeIdx arg) override;
	void dispatchArrayCopy(WASM::TypeIdx arg1, WASM::TypeIdx arg2) override;
	void dispatchArrayInitData(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchArrayInitElem(WASM::TypeIdx arg1, uint32_t arg2) override;
	void dispatchRefTest(const WASM::HeapType& arg) override;
	void dispatchRefTestNull(const WASM::HeapType& arg) override;
	void dispatchRefCast(const WASM::HeapType& arg) override;
	void dispatchRefCastNull(const WASM::HeapType& arg) override;
	void dispatchBrOnCast(uint8_t castop, WASM::LabelIdx l, WASM::HeapType ht1, WASM::HeapType ht2) override;
	void dispatchBrOnCastFail(uint8_t castop, WASM::LabelIdx l, WASM::HeapType ht1, WASM::HeapType ht2) override;
	void dispatchAnyConvertExtern() override;
	void dispatchExternConvertAny() override;
	void dispatchRefI31() override;
	void dispatchI31GetS() override;
	void dispatchI31GetU() override;
	void dispatchI32TruncSatF32S() override;
	void dispatchI32TruncSatF32U() override;
	void dispatchI32TruncSatF64S() override;
	void dispatchI32TruncSatF64U() override;
	void dispatchI64TruncSatF32S() override;
	void dispatchI64TruncSatF32U() override;
	void dispatchI64TruncSatF64S() override;
	void dispatchI64TruncSatF64U() override;
	void dispatchMemoryInit(uint32_t arg1, WASM::MemIdx arg2) override;
	void dispatchDataDrop(uint32_t arg) override;
	void dispatchMemoryCopy(WASM::MemIdx arg1, WASM::MemIdx arg2) override;
	void dispatchMemoryFill(WASM::MemIdx arg) override;
	void dispatchTableInit(uint32_t arg1, WASM::TableIdx arg2) override;
	void dispatchElemDrop(uint32_t arg) override;
	void dispatchTableCopy(WASM::TableIdx arg1, WASM::TableIdx arg2) override;
	void dispatchTableGrow(WASM::TableIdx arg) override;
	void dispatchTableSize(WASM::TableIdx arg) override;
	void dispatchTableFill(WASM::TableIdx arg) override;
	void dispatchV128Load(WASM::MemArg arg) override;
	void dispatchV128Load8x8S(WASM::MemArg arg) override;
	void dispatchV128Load8x8U(WASM::MemArg arg) override;
	void dispatchV128Load16x4S(WASM::MemArg arg) override;
	void dispatchV128Load16x4U(WASM::MemArg arg) override;
	void dispatchV128Load32x2S(WASM::MemArg arg) override;
	void dispatchV128Load32x2U(WASM::MemArg arg) override;
	void dispatchV128Load8Splat(WASM::MemArg arg) override;
	void dispatchV128Load16Splat(WASM::MemArg arg) override;
	void dispatchV128Load32Splat(WASM::MemArg arg) override;
	void dispatchV128Load64Splat(WASM::MemArg arg) override;
	void dispatchV128Load32Zero(WASM::MemArg arg) override;
	void dispatchV128Load64Zero(WASM::MemArg arg) override;
	void dispatchV128Store(WASM::MemArg arg) override;
	void dispatchV128Load8Lane(WASM::MemArg arg1, uint8_t arg2) override;
	void dispatchV128Load16Lane(WASM::MemArg arg1, uint8_t arg2) override;
	void dispatchV128Load32Lane(WASM::MemArg arg1, uint8_t arg2) override;
	void dispatchV128Load64Lane(WASM::MemArg arg1, uint8_t arg2) override;
	void dispatchV128Store8Lane(WASM::MemArg arg1, uint8_t arg2) override;
	void dispatchV128Store16Lane(WASM::MemArg arg1, uint8_t arg2) override;
	void dispatchV128Store32Lane(WASM::MemArg arg1, uint8_t arg2) override;
	void dispatchV128Store64Lane(WASM::MemArg arg1, uint8_t arg2) override;
	void dispatchV128Const(std::span<uint8_t> arg) override;
	void dispatchI8x16Shuffle(std::span<uint8_t> arg) override;
	void dispatchI8x16Swizzle() override;
	void dispatchI8x16Splat() override;
	void dispatchI16x8Splat() override;
	void dispatchI32x4Splat() override;
	void dispatchI64x2Splat() override;
	void dispatchF32x4Splat() override;
	void dispatchF64x2Splat() override;
	void dispatchI8x16ExtractLaneS(uint8_t arg) override;
	void dispatchI8x16ExtractLaneU(uint8_t arg) override;
	void dispatchI8x16ReplaceLane(uint8_t arg) override;
	void dispatchI16x8ExtractLaneS(uint8_t arg) override;
	void dispatchI16x8ExtractLaneU(uint8_t arg) override;
	void dispatchI16x8ReplaceLane(uint8_t arg) override;
	void dispatchI32x4ExtractLane(uint8_t arg) override;
	void dispatchI32x4ReplaceLane(uint8_t arg) override;
	void dispatchI64x2ExtractLane(uint8_t arg) override;
	void dispatchI64x2ReplaceLane(uint8_t arg) override;
	void dispatchF32x4ExtractLane(uint8_t arg) override;
	void dispatchF32x4ReplaceLane(uint8_t arg) override;
	void dispatchF64x2ExtractLane(uint8_t arg) override;
	void dispatchF64x2ReplaceLane(uint8_t arg) override;
	void dispatchI8x16Eq() override;
	void dispatchI8x16Ne() override;
	void dispatchI8x16LtS() override;
	void dispatchI8x16LtU() override;
	void dispatchI8x16GtS() override;
	void dispatchI8x16GtU() override;
	void dispatchI8x16LeS() override;
	void dispatchI8x16LeU() override;
	void dispatchI8x16GeS() override;
	void dispatchI8x16GeU() override;
	void dispatchI16x8Eq() override;
	void dispatchI16x8Ne() override;
	void dispatchI16x8LtS() override;
	void dispatchI16x8LtU() override;
	void dispatchI16x8GtS() override;
	void dispatchI16x8GtU() override;
	void dispatchI16x8LeS() override;
	void dispatchI16x8LeU() override;
	void dispatchI16x8GeS() override;
	void dispatchI16x8GeU() override;
	void dispatchI32x4Eq() override;
	void dispatchI32x4Ne() override;
	void dispatchI32x4LtS() override;
	void dispatchI32x4LtU() override;
	void dispatchI32x4GtS() override;
	void dispatchI32x4GtU() override;
	void dispatchI32x4LeS() override;
	void dispatchI32x4LeU() override;
	void dispatchI32x4GeS() override;
	void dispatchI32x4GeU() override;
	void dispatchF32x4Eq() override;
	void dispatchF32x4Ne() override;
	void dispatchF32x4Lt() override;
	void dispatchF32x4Gt() override;
	void dispatchF32x4Le() override;
	void dispatchF32x4Ge() override;
	void dispatchF64x2Eq() override;
	void dispatchF64x2Ne() override;
	void dispatchF64x2Lt() override;
	void dispatchF64x2Gt() override;
	void dispatchF64x2Le() override;
	void dispatchF64x2Ge() override;
	void dispatchV128Not() override;
	void dispatchV128And() override;
	void dispatchV128AndNot() override;
	void dispatchV128Or() override;
	void dispatchV128Xor() override;
	void dispatchV128Bitselect() override;
	void dispatchV128AnyTrue() override;
	void dispatchI8x16Abs() override;
	void dispatchI8x16Neg() override;
	void dispatchI8x16Popcnt() override;
	void dispatchI8x16AllTrue() override;
	void dispatchI8x16Bitmask() override;
	void dispatchI8x16NarrowI16x8S() override;
	void dispatchI8x16NarrowI16x8U() override;
	void dispatchI8x16Shl() override;
	void dispatchI8x16ShrS() override;
	void dispatchI8x16ShrU() override;
	void dispatchI8x16Add() override;
	void dispatchI8x16AddSatS() override;
	void dispatchI8x16AddSatU() override;
	void dispatchI8x16Sub() override;
	void dispatchI8x16SubSatS() override;
	void dispatchI8x16SubSatU() override;
	void dispatchI8x16MinS() override;
	void dispatchI8x16MinU() override;
	void dispatchI8x16MaxS() override;
	void dispatchI8x16MaxU() override;
	void dispatchI8x16AvgrU() override;
	void dispatchI16x8ExtAddPairwiseI8x16S() override;
	void dispatchI16x8ExtAddPairwiseI8x16U() override;
	void dispatchI16x8Abs() override;
	void dispatchI16x8Neg() override;
	void dispatchI16x8Q15MulRSatS() override;
	void dispatchI16x8AllTrue() override;
	void dispatchI16x8Bitmask() override;
	void dispatchI16x8NarrowI32x4S() override;
	void dispatchI16x8NarrowI32x4U() override;
	void dispatchI16x8ExtendLowI8x16S() override;
	void dispatchI16x8ExtendHighI8x16S() override;
	void dispatchI16x8ExtendLowI8x16U() override;
	void dispatchI16x8ExtendHighI8x16U() override;
	void dispatchI16x8Shl() override;
	void dispatchI16x8ShrS() override;
	void dispatchI16x8ShrU() override;
	void dispatchI16x8Add() override;
	void dispatchI16x8AddSatS() override;
	void dispatchI16x8AddSatU() override;
	void dispatchI16x8Sub() override;
	void dispatchI16x8SubSatS() override;
	void dispatchI16x8SubSatU() override;
	void dispatchI16x8Mul() override;
	void dispatchI16x8MinS() override;
	void dispatchI16x8MinU() override;
	void dispatchI16x8MaxS() override;
	void dispatchI16x8MaxU() override;
	void dispatchI16x8AvgrU() override;
	void dispatchI16x8ExtMulLowI8x16S() override;
	void dispatchI16x8ExtMulHighI8x16S() override;
	void dispatchI16x8ExtMulLowI8x16U() override;
	void dispatchI16x8ExtMulHighI8x16U() override;
	void dispatchI32x4ExtAddPairwiseI16x8S() override;
	void dispatchI32x4ExtAddPairwiseI16x8U() override;
	void dispatchI32x4Abs() override;
	void dispatchI32x4Neg() override;
	void dispatchI32x4AllTrue() override;
	void dispatchI32x4Bitmask() override;
	void dispatchI32x4ExtendLowI16x8S() override;
	void dispatchI32x4ExtendHighI16x8S() override;
	void dispatchI32x4ExtendLowI16x8U() override;
	void dispatchI32x4ExtendHighI16x8U() override;
	void dispatchI32x4Shl() override;
	void dispatchI32x4ShrS() override;
	void dispatchI32x4ShrU() override;
	void dispatchI32x4Add() override;
	void dispatchI32x4Sub() override;
	void dispatchI32x4Mul() override;
	void dispatchI32x4MinS() override;
	void dispatchI32x4MinU() override;
	void dispatchI32x4MaxS() override;
	void dispatchI32x4MaxU() override;
	void dispatchI32x4DotI16x8S() override;
	void dispatchI32x4ExtMulLowI16x8S() override;
	void dispatchI32x4ExtMulHighI16x8S() override;
	void dispatchI32x4ExtMulLowI16x8U() override;
	void dispatchI32x4ExtMulHighI16x8U() override;
	void dispatchI64x2Abs() override;
	void dispatchI64x2Neg() override;
	void dispatchI64x2AllTrue() override;
	void dispatchI64x2Bitmask() override;
	void dispatchI64x2ExtendLowI32x4S() override;
	void dispatchI64x2ExtendHighI32x4S() override;
	void dispatchI64x2ExtendLowI32x4U() override;
	void dispatchI64x2ExtendHighI32x4U() override;
	void dispatchI64x2Shl() override;
	void dispatchI64x2ShrS() override;
	void dispatchI64x2ShrU() override;
	void dispatchI64x2Add() override;
	void dispatchI64x2Sub() override;
	void dispatchI64x2Mul() override;
	void dispatchI64x2Eq() override;
	void dispatchI64x2Ne() override;
	void dispatchI64x2LtS() override;
	void dispatchI64x2GtS() override;
	void dispatchI64x2LeS() override;
	void dispatchI64x2GeS() override;
	void dispatchI64x2ExtMulLowI32x4S() override;
	void dispatchI64x2ExtMulHighI32x4S() override;
	void dispatchI64x2ExtMulLowI32x4U() override;
	void dispatchI64x2ExtMulHighI32x4U() override;
	void dispatchF32x4Ceil() override;
	void dispatchF32x4Floor() override;
	void dispatchF32x4Trunc() override;
	void dispatchF32x4Nearest() override;
	void dispatchF32x4Abs() override;
	void dispatchF32x4Neg() override;
	void dispatchF32x4Sqrt() override;
	void dispatchF32x4Add() override;
	void dispatchF32x4Sub() override;
	void dispatchF32x4Mul() override;
	void dispatchF32x4Div() override;
	void dispatchF32x4Min() override;
	void dispatchF32x4Max() override;
	void dispatchF32x4PMin() override;
	void dispatchF32x4PMax() override;
	void dispatchF64x2Ceil() override;
	void dispatchF64x2Floor() override;
	void dispatchF64x2Trunc() override;
	void dispatchF64x2Nearest() override;
	void dispatchF64x2Abs() override;
	void dispatchF64x2Neg() override;
	void dispatchF64x2Sqrt() override;
	void dispatchF64x2Add() override;
	void dispatchF64x2Sub() override;
	void dispatchF64x2Mul() override;
	void dispatchF64x2Div() override;
	void dispatchF64x2Min() override;
	void dispatchF64x2Max() override;
	void dispatchF64x2PMin() override;
	void dispatchF64x2PMax() override;
	void dispatchI32x4TruncSatF32x4S() override;
	void dispatchI32x4TruncSatF32x4U() override;
	void dispatchF32x4ConvertI32x4S() override;
	void dispatchF32x4ConvertI32x4U() override;
	void dispatchI32x4TruncSatF64x2SZero() override;
	void dispatchI32x4TruncSatF64x2UZero() override;
	void dispatchF64x2ConvertLowI32x4S() override;
	void dispatchF64x2ConvertLowI32x4U() override;
	void dispatchF32x4DemoteF64x2Zero() override;
	void dispatchF64x2PromoteLowF32x4() override;
	void dispatchMemoryAtomicNotify(WASM::MemArg arg) override;
	void dispatchMemoryAtomicWait32(WASM::MemArg arg) override;
	void dispatchMemoryAtomicWait64(WASM::MemArg arg) override;
	void dispatchAtomicFence() override;
	void dispatchI32AtomicLoad(WASM::MemArg arg) override;
	void dispatchI64AtomicLoad(WASM::MemArg arg) override;
	void dispatchI32AtomicLoad8U(WASM::MemArg arg) override;
	void dispatchI32AtomicLoad16U(WASM::MemArg arg) override;
	void dispatchI64AtomicLoad8U(WASM::MemArg arg) override;
	void dispatchI64AtomicLoad16U(WASM::MemArg arg) override;
	void dispatchI64AtomicLoad32U(WASM::MemArg arg) override;
	void dispatchI32AtomicStore(WASM::MemArg arg) override;
	void dispatchI64AtomicStore(WASM::MemArg arg) override;
	void dispatchI32AtomicStore8(WASM::MemArg arg) override;
	void dispatchI32AtomicStore16(WASM::MemArg arg) override;
	void dispatchI64AtomicStore8(WASM::MemArg arg) override;
	void dispatchI64AtomicStore16(WASM::MemArg arg) override;
	void dispatchI64AtomicStore32(WASM::MemArg arg) override;
	void dispatchI32AtomicRmwAdd(WASM::MemArg arg) override;
	void dispatchI64AtomicRmwAdd(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw8AddU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw16AddU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw8AddU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw16AddU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw32AddU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmwSub(WASM::MemArg arg) override;
	void dispatchI64AtomicRmwSub(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw8SubU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw16SubU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw8SubU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw16SubU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw32SubU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmwAnd(WASM::MemArg arg) override;
	void dispatchI64AtomicRmwAnd(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw8AndU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw16AndU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw8AndU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw16AndU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw32AndU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmwOr(WASM::MemArg arg) override;
	void dispatchI64AtomicRmwOr(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw8OrU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw16OrU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw8OrU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw16OrU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw32OrU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmwXor(WASM::MemArg arg) override;
	void dispatchI64AtomicRmwXor(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw8XorU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw16XorU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw8XorU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw16XorU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw32XorU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmwXchg(WASM::MemArg arg) override;
	void dispatchI64AtomicRmwXchg(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw8XchgU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw16XchgU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw8XchgU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw16XchgU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw32XchgU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmwCmpxchg(WASM::MemArg arg) override;
	void dispatchI64AtomicRmwCmpxchg(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw8CmpxchgU(WASM::MemArg arg) override;
	void dispatchI32AtomicRmw16CmpxchgU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw8CmpxchgU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw16CmpxchgU(WASM::MemArg arg) override;
	void dispatchI64AtomicRmw32CmpxchgU(WASM::MemArg arg) override;
};

}

#endif // LIBJITOPCODEDISPATCHER_HPP
